Clean up to slim concept second part
removes quicksearchbox, openwnn......

Change-Id: I9a989fb2105a185215da6335feeb2b880e26963b

diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -19,8 +19,8 @@ else
 fi
 
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-	echo "ERROR: $0 only works with a full build environment. $OUT should exist."
-	exit 1
+    echo "ERROR: $0 only works with a full build environment. $OUT should exist."
+    exit 1
 fi
 
 if [ "$TARGET_BUILD_TYPE" = "debug" ]; then
@@ -41,7 +41,7 @@ OPTICHARGER=$ANDROID_BUILD_TOP/vendor/slim/tools/opticharger
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 DELETE_MEDIA="*.qmg"
-DELETE_APKS="Launcher2.apk LiveWallpapers.apk VoiceDialer.apk SoundRecorder.apk VisualizationWallpapers.apk VideoEditor.apk Exchange2.apk HoloSpiralWallpaper.apk HTMLViewer.apk MagicSmokeWallpapers.apk NoiseField.apk PicoTts.apk "
+DELETE_APKS="Launcher2.apk LiveWallpapers.apk VoiceDialer.apk SoundRecorder.apk VisualizationWallpapers.apk VideoEditor.apk Exchange2.apk HoloSpiralWallpaper.apk MagicSmokeWallpapers.apk NoiseField.apk Calendar.apk OpenWnn.apk PinyinIME.apk QuickSearchBox.apk"
 DELETE_GALLERY="Gallery2.apk"
 DELETE_FONTS="MTLmr3m.ttf NanumGothic.ttf"
 
